# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turtlecmd.ui'
#
# Created: Wed Sep 30 12:48:27 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(20, 390, 751, 141))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.ANY_lbl = QtGui.QLabel(self.widget_2)
        self.ANY_lbl.setGeometry(QtCore.QRect(10, 10, 58, 17))
        self.ANY_lbl.setObjectName(_fromUtf8("ANY_lbl"))
        self.TODO_lbl = QtGui.QLabel(self.widget_2)
        self.TODO_lbl.setGeometry(QtCore.QRect(210, 50, 121, 17))
        self.TODO_lbl.setObjectName(_fromUtf8("TODO_lbl"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 751, 361))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pose_x_lcd = QtGui.QLCDNumber(self.tab)
        self.pose_x_lcd.setGeometry(QtCore.QRect(20, 20, 64, 23))
        self.pose_x_lcd.setObjectName(_fromUtf8("pose_x_lcd"))
        self.pose_y_lcd = QtGui.QLCDNumber(self.tab)
        self.pose_y_lcd.setGeometry(QtCore.QRect(20, 60, 64, 23))
        self.pose_y_lcd.setObjectName(_fromUtf8("pose_y_lcd"))
        self.pose_x_lbl = QtGui.QLabel(self.tab)
        self.pose_x_lbl.setGeometry(QtCore.QRect(90, 20, 58, 17))
        self.pose_x_lbl.setObjectName(_fromUtf8("pose_x_lbl"))
        self.pose_y_lbl = QtGui.QLabel(self.tab)
        self.pose_y_lbl.setGeometry(QtCore.QRect(90, 60, 58, 17))
        self.pose_y_lbl.setObjectName(_fromUtf8("pose_y_lbl"))
        self.cmd_linear_x_sbx = QtGui.QSpinBox(self.tab)
        self.cmd_linear_x_sbx.setGeometry(QtCore.QRect(470, 50, 52, 27))
        self.cmd_linear_x_sbx.setObjectName(_fromUtf8("cmd_linear_x_sbx"))
        self.pose_theta_lcd = QtGui.QLCDNumber(self.tab)
        self.pose_theta_lcd.setGeometry(QtCore.QRect(20, 100, 64, 23))
        self.pose_theta_lcd.setObjectName(_fromUtf8("pose_theta_lcd"))
        self.pose_tetha_lbl = QtGui.QLabel(self.tab)
        self.pose_tetha_lbl.setGeometry(QtCore.QRect(90, 100, 58, 17))
        self.pose_tetha_lbl.setObjectName(_fromUtf8("pose_tetha_lbl"))
        self.pose_linear_lcd = QtGui.QLCDNumber(self.tab)
        self.pose_linear_lcd.setGeometry(QtCore.QRect(20, 170, 64, 23))
        self.pose_linear_lcd.setObjectName(_fromUtf8("pose_linear_lcd"))
        self.pose_linear_lbl = QtGui.QLabel(self.tab)
        self.pose_linear_lbl.setGeometry(QtCore.QRect(90, 170, 58, 17))
        self.pose_linear_lbl.setObjectName(_fromUtf8("pose_linear_lbl"))
        self.pose_angular_lcd = QtGui.QLCDNumber(self.tab)
        self.pose_angular_lcd.setGeometry(QtCore.QRect(20, 210, 64, 23))
        self.pose_angular_lcd.setObjectName(_fromUtf8("pose_angular_lcd"))
        self.pose_angular_lbl = QtGui.QLabel(self.tab)
        self.pose_angular_lbl.setGeometry(QtCore.QRect(90, 210, 58, 17))
        self.pose_angular_lbl.setObjectName(_fromUtf8("pose_angular_lbl"))
        self.cmd_linea_x_lbl = QtGui.QLabel(self.tab)
        self.cmd_linea_x_lbl.setGeometry(QtCore.QRect(530, 50, 58, 17))
        self.cmd_linea_x_lbl.setObjectName(_fromUtf8("cmd_linea_x_lbl"))
        self.cmd_linear_y_sbx = QtGui.QSpinBox(self.tab)
        self.cmd_linear_y_sbx.setGeometry(QtCore.QRect(470, 90, 52, 27))
        self.cmd_linear_y_sbx.setObjectName(_fromUtf8("cmd_linear_y_sbx"))
        self.cmd_linear_y_lbl = QtGui.QLabel(self.tab)
        self.cmd_linear_y_lbl.setGeometry(QtCore.QRect(530, 90, 58, 17))
        self.cmd_linear_y_lbl.setObjectName(_fromUtf8("cmd_linear_y_lbl"))
        self.cmd_linear_z_sbx = QtGui.QSpinBox(self.tab)
        self.cmd_linear_z_sbx.setGeometry(QtCore.QRect(470, 130, 52, 27))
        self.cmd_linear_z_sbx.setObjectName(_fromUtf8("cmd_linear_z_sbx"))
        self.cmd_linear_z_lbl = QtGui.QLabel(self.tab)
        self.cmd_linear_z_lbl.setGeometry(QtCore.QRect(530, 130, 58, 17))
        self.cmd_linear_z_lbl.setObjectName(_fromUtf8("cmd_linear_z_lbl"))
        self.cmd_angular_z_lbl = QtGui.QLabel(self.tab)
        self.cmd_angular_z_lbl.setGeometry(QtCore.QRect(670, 130, 58, 17))
        self.cmd_angular_z_lbl.setObjectName(_fromUtf8("cmd_angular_z_lbl"))
        self.cmd_angular_lbl = QtGui.QLabel(self.tab)
        self.cmd_angular_lbl.setGeometry(QtCore.QRect(670, 90, 58, 17))
        self.cmd_angular_lbl.setObjectName(_fromUtf8("cmd_angular_lbl"))
        self.cmd_angular_z_sbx = QtGui.QSpinBox(self.tab)
        self.cmd_angular_z_sbx.setGeometry(QtCore.QRect(610, 130, 52, 27))
        self.cmd_angular_z_sbx.setObjectName(_fromUtf8("cmd_angular_z_sbx"))
        self.cmd_angular_x_sbx = QtGui.QSpinBox(self.tab)
        self.cmd_angular_x_sbx.setGeometry(QtCore.QRect(610, 50, 52, 27))
        self.cmd_angular_x_sbx.setObjectName(_fromUtf8("cmd_angular_x_sbx"))
        self.cmd_angular_y_sbx = QtGui.QSpinBox(self.tab)
        self.cmd_angular_y_sbx.setGeometry(QtCore.QRect(610, 90, 52, 27))
        self.cmd_angular_y_sbx.setObjectName(_fromUtf8("cmd_angular_y_sbx"))
        self.cmd_angular_x_lbl = QtGui.QLabel(self.tab)
        self.cmd_angular_x_lbl.setGeometry(QtCore.QRect(670, 50, 58, 17))
        self.cmd_angular_x_lbl.setObjectName(_fromUtf8("cmd_angular_x_lbl"))
        self.cmd_linear_lbl = QtGui.QLabel(self.tab)
        self.cmd_linear_lbl.setGeometry(QtCore.QRect(470, 10, 58, 17))
        self.cmd_linear_lbl.setObjectName(_fromUtf8("cmd_linear_lbl"))
        self.cmd_Angular_lbl = QtGui.QLabel(self.tab)
        self.cmd_Angular_lbl.setGeometry(QtCore.QRect(610, 10, 58, 17))
        self.cmd_Angular_lbl.setObjectName(_fromUtf8("cmd_Angular_lbl"))
        self.send_cmd_btn = QtGui.QPushButton(self.tab)
        self.send_cmd_btn.setGeometry(QtCore.QRect(510, 200, 121, 31))
        self.send_cmd_btn.setObjectName(_fromUtf8("send_cmd_btn"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ANY_lbl.setText(_translate("MainWindow", "ANY", None))
        self.TODO_lbl.setText(_translate("MainWindow", "TODO : Actions", None))
        self.pose_x_lbl.setText(_translate("MainWindow", "X", None))
        self.pose_y_lbl.setText(_translate("MainWindow", "Y", None))
        self.pose_tetha_lbl.setText(_translate("MainWindow", "theta", None))
        self.pose_linear_lbl.setText(_translate("MainWindow", "linear", None))
        self.pose_angular_lbl.setText(_translate("MainWindow", "angular", None))
        self.cmd_linea_x_lbl.setText(_translate("MainWindow", "X", None))
        self.cmd_linear_y_lbl.setText(_translate("MainWindow", "Y", None))
        self.cmd_linear_z_lbl.setText(_translate("MainWindow", "Z", None))
        self.cmd_angular_z_lbl.setText(_translate("MainWindow", "Z", None))
        self.cmd_angular_lbl.setText(_translate("MainWindow", "Y", None))
        self.cmd_angular_x_lbl.setText(_translate("MainWindow", "X", None))
        self.cmd_linear_lbl.setText(_translate("MainWindow", "Linear", None))
        self.cmd_Angular_lbl.setText(_translate("MainWindow", "Angular", None))
        self.send_cmd_btn.setText(_translate("MainWindow", "Send Command", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))

