#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

# to help debugging this
#echo $*

#necessary to handle arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -b|--broker)
    BROKER="$2"
    shift 2
    ;;
    -A|--app)
    APP="$2"
    shift 2
    ;;
    -c|--config)
    CONFIG="$2"
    shift 2
    ;;
    -S|--scheduler)
    SCHEDULER_CLS="$2"
    shift 2
    ;;
    -l|--loglevel)
    LOG="$2"
    shift 2
    ;;
    __*)
    ROSARGS="${ROSARGS:+$ROSARGS} --ros-arg=$key"
    #ros option ( multiple )
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option"
    shift 1
    ;;
esac
done

BROKER=${BROKER:+"-b $BROKER"}
APP=${APP:+"-A $APP"}
CONFIG=${CONFIG:+"--config=$CONFIG"}
SCHEDULER_CLS=${SCHEDULER_CLS:+"-S $SCHEDULER_CLS"}
LOG=${LOG:+"-l $LOG"}
set -x

# we ignore rosargs
python -tt -m celery ${APP} beat ${BROKER} ${CONFIG} ${SCHEDULER_CLS} ${LOG}

