#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

# to help debugging this
#echo $*

#necessary to handle arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -h|--hostname)
    CELEROS_HOSTNAME="$2"
    shift 2
    ;;
    -b|--broker)
    BROKER="$2"
    shift 2
    ;;
    -B|--beat)
    BEAT="$key"
    shift 1
    ;;
    -A|--app)
    APP="$2"
    shift 2
    ;;
    -c|--config)
    CONFIG="$2"
    shift 2
    ;;
    -Q|--queues)
    QUEUES="$2"
    shift 2
    ;;
    -S|--scheduler)
    SCHEDULER_CLS="$2"
    shift 2
    ;;
    -l|--loglevel)
    LOG="$2"
    shift 2
    ;;
    __*)
    ROSARGS="${ROSARGS:+$ROSARGS} --ros-arg=$key"
    #ros option ( multiple )
    shift 1
    ;;
    ~*)  # matching relative remapping ros args
    ROSARGS="${ROSARGS:+$ROSARGS} --ros-arg=$key"
    #ros option (multiple)
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option $key"
    shift 1
    ;;
esac
done

BROKER=${BROKER:+"-b $BROKER"}
APP=${APP:+"-A $APP"}
CONFIG=${CONFIG:+"--config=$CONFIG"}
CELEROS_HOSTNAME=${CELEROS_HOSTNAME:+"-n $CELEROS_HOSTNAME"}
SCHEDULER_CLS=${SCHEDULER_CLS:+"-S $SCHEDULER_CLS"}
QUEUES=${QUEUES:+"-Q $QUEUES"}
LOG=${LOG:+"-l $LOG"}
set -x

python -tt -m celery ${APP} worker ${BEAT} ${BROKER} ${CONFIG} ${QUEUES} ${CELEROS_HOSTNAME} ${ROSARGS} ${LOG}
