#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

# to help debugging this
#echo $*

#TODO : integrate with worker or beat so starting celeros always start flower (useful for monitoring and debugging)

#necessary to handle Click arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    --port)
    PORT="$2"
    shift 2
    ;;
    --address)
    ADDRESS="$2"
    shift 2
    ;;
    --conf)
    CONF="$2"
    shift 2
    ;;
    --config)
    CONFIG="$2"
    shift 2
    ;;
    -b|--broker)
    BROKER="$2"
    shift 2
    ;;
    -A|--app)
    APP="$2"
    shift 2
    ;;
    -l|--logging)
    LOG="$2"
    shift 2
    ;;
    __log:=*)
    ROSLOG=${key#*:=}
    #ros log option as prefix
    shift 1
    ;;
    __name:=*)
    # ignoring
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option $key"
    shift 1
    ;;
esac
done

PORT=${PORT:+"--port=$PORT"}
ADDRESS=${ADDRESS:+"--address=$ADDRESS"}
CONF=${CONF:+"--conf=$CONF"}
CONFIG=${CONFIG:+"--config=$CONFIG"}
BROKER=${BROKER:+"-b $BROKER"}
APP=${APP:+"-A $APP"}
LOG=${LOG:+"--logging=$LOG"}
ROSLOG=${ROSLOG:+"--log_file_prefix=$ROSLOG"}

set -x

# need to call python to use the flower version accessible after  "source <devel|install>/setup.bash"
python -tt -m flower ${PORT} ${ADDRESS} ${CONF} ${CONFIG} ${BROKER} ${TASKS} ${ROSARGS} ${LOG} ${ROSLOG}

