#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

echo $*

#necessary to handle arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -h|--hostname)
    CELEROS_HOSTNAME="$2"
    shift 2
    ;;
    -b|--broker-url)
    BROKER="$2"
    shift 2
    ;;
    -t|--worker-tasks)
    TASKS="$2"
    shift 2
    ;;
    -c|--worker-config)
    CONFIG="$2"
    shift 2
    ;;
    -Q|--queues)
    QUEUES="$2"
    shift 2
    ;;
    -l|--loglevel)
    LOG="$2"
    shift 2
    ;;
    __*)
    ROSARGS="${ROSARGS:+$ROSARGS} --ros-arg=$key"
    #ros option ( multiple )
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option"
    shift 1
    ;;
esac
done

BROKER=${BROKER:+"-b $BROKER"}
TASKS=${TASKS:+"-A $TASKS"}
CONFIG=${CONFIG:+"--config=$CONFIG"}
CELEROS_HOSTNAME=${CELEROS_HOSTNAME:+"-n $CELEROS_HOSTNAME"}
QUEUES=${QUEUES:+"-Q $QUEUES"}
LOG=${QUEUES:+"-l $LOG"}
set -x

python -tt -m celery worker ${BROKER} ${TASKS} ${CONFIG} ${QUEUES} ${CELEROS_HOSTNAME} ${ROSARGS} -c 1 ${LOG}
